_target_: src.shift.manager.ShiftInterventionManager

mode: collect

blocks:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18

steps:
  - 0

controller: null

collector:
  _target_: src.shift.collector.PooledSVMDatasetCollector

  save_dir: ${hydra:runtime.output_dir}/svm_dataset
  tensor_dtype: float32
  concept_name: cyberpunk